#
# {{ ansible_managed }}
#
---
parameters:
  groups:
    desc: "The ansible groups to used to select hosts"
    format: "List of groups separated by comma or group pattern"
  type:
    desc: "The type of search"
    choices:
      - "list"
      - "regex"
    default: "list"
  sources:
    desc: "List of folder or ansible inventories files to request"
    default:
      - "/etc/ansible/hosts"
#       - "/home/liftree/ansible-ws/test/data/inventories"
  format:
    desc: "The output format of json results"
    choices:
      - "sui"
      - "raw"
    default: "sui"
  groups_selection:
    desc: "To allow group selection"
    choices:
      - "yes"
      - "no"
    default: "yes"
examples:
  - desc: "To have help"
    url: "http://192.168.1.19:8081"
  - desc: "To get all hosts"
    url: "http://192.168.1.19:8081?groups=all"
  - desc: "To get hosts in groups database_app1_prod and database_app2_dev"
    url: "http://192.168.1.19:8081?groups=database_app1_prod,database_app3_prod"
  - desc: "To get hosts wich name groups match pattern database_.*_prod"
    url: "http://192.168.1.19:8081?groups=database_.*_prod"
...
