---
### DOC ### author: olivier perriot
### DOC ### state: dev
### DOC ### description: |
### DOC ###   Deploy wsgi application

- hosts: localhost
  gather_facts: true
  roles:
    - setup

...
